sudo: false
language: node_js
node_js: stable
script:
  - yarn run build:browser
after_success:
  - |

        $(npm bin)/set-up-ssh --key "$encrypted_d5d527d3f6a6_key" \
                             --iv "$encrypted_d5d527d3f6a6_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

        $(npm bin)/update-branch --commands "npm run build" \
                                 --commit-message "Update website [skip ci]" \
                                 --directory "./public" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"
