osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "10"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - libsecret-1-0

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
- yarn install

script:
  - yarn test
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release -- --mac --win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
