osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - libsecret-1-0

before_install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

jobs:
  fast_finish: true
  include:
    # Test
    - stage: test
      script: yarn run ci
    # Deploy
    - stage: deploy
      os: linux
      scripts:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release; fi
    - stage: deploy
      os: osx
      scripts:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release -- --mac --win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
after_success:
  - |

        $(npm bin)/set-up-ssh --key "$encrypted_d5d527d3f6a6_key" \
                             --iv "$encrypted_d5d527d3f6a6_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"

        $(npm bin)/update-branch --commands "yarn run build:browser && yarn run build:docs" \
                                 --commit-message "Update website [skip ci]" \
                                 --directory "./public" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"